apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-test-server-app
  namespace: default
  labels:
    app: docker-test-server-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-test-server-app
  template:
    metadata:
      labels:
        app: docker-test-server-app
    spec:
      containers:
        - name: docker-test-server-app
          image: theraaz/docker-test-server:$COMMIT_SHA1
          ports:
            - containerPort: 3000
              name: http