apiVersion: v1
kind: Service
metadata:
  name: docker-test-server-app
  namespace: default
  labels:
    app: docker-test-server-app
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: http
      name: http
  selector:
    app: docker-test-server-app